### ISSUE TITLE
Escaping percent characters in input files

### ISSUE THREAD

**Issue by aerben** [DannyBen/kojo#38]
I hope that I did not miss anything in the documentation, but I'm struggling with using Kojo on files that contain percent characters that should not be interpreted as variable placeholders. When using a template file like

```
(...)
- name: Apply env variables
  run: |
    BUILDDATE=$(echo "$(date +%Y%m%d)")
    BUILDTIME=$(echo "$(date +%H%M%S)")
```

kojo will fail with the following error:
```
kojo file template.yml
Kojo::TemplateError
malformed format string - %Y
in: build-master-int-pre-prod.yml
```

How to escape the offending character?

**Comment by DannyBen** [comment]
Hi. 

Even if you missed something in the documentation, it might mean the documentation needs some update... :)

Since these files are going ruby string interpolation (for the `%{arg}` replacement), literal percent signs need to be denoted as `%%`. 

In addition, I am not sure you need the `echo` in your code, but I might be wrong.

Here is a sample:

```yaml
# template.yml
test:
- name: Apply env variables
  run: |
    BUILDDATE=$(echo "$(date +%%Y%%m%%d)")
    BUILDTIME=$(echo "$(date +%%H%%M%%S)"

- name: 
  run: |
    BUILDDATE="$(date +%%Y%%m%%d)"
    BUILDTIME="$(date +%%H%%M%%S)"
```

Output:

```
$ kojo file template.yml
test:
- name: Apply env variables
  run: |
    BUILDDATE=$(echo "$(date +%Y%m%d)")
    BUILDTIME=$(echo "$(date +%H%M%S)"

- name:
  run: |
    BUILDDATE="$(date +%Y%m%d)"
    BUILDTIME="$(date +%H%M%S)"
```

Is this what you needed?

If so, I will update the docs to mention this. Sometimes I forget that kojo users might not be familiar with some of Ruby's features.
